services:
  postgres:
    image: postgres:15
    container_name: todonest_postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todonest
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
